apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-capture-api
  namespace: app1
spec:
  selector:
      matchLabels:
        app: order-capture-api
  template:
      metadata:
        labels:
            app: capture-order-api
      spec:
        imagePullSecrets:
        - name: acr-auth
        containers:
        - name: order-capture-api
          image: mdpacrpcc.azurecr.io/captureorder # replace with your own repository
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              port: 8080
              path: /healthz
          livenessProbe:
            httpGet:
              port: 8080
              path: /healthz
          resources:
            requests:
              memory: "150Mi"
              cpu: "1"
            limits:
              memory: "250Mi"
              cpu: "1"
          env:
          - name: TEAMNAME
            value: 'PDM-IS-COOL' # will be patched at deployment time by value of 'teamName' in the variable group
          - name: MONGOHOST
            valueFrom:
              secretKeyRef:
                name: mongodb
                key: mongoHost
          - name: MONGOUSER
            valueFrom:
              secretKeyRef:
                name: mongodb
                key: mongoUser
          - name: MONGOPASSWORD
            valueFrom:
              secretKeyRef:
                name: mongodb
                key: mongoPassword
          ports:
          - containerPort: 80
