apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: captureorder
  namespace: app1
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: order-capture-api
  minReplicas: 15
  maxReplicas: 30
  targetCPUUtilizationPercentage: 75
