apiVersion: v1
kind: Service
metadata:
  name: captureorder
  namespace: app1
spec:   
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  selector:
    app: order-capture-api
